# This file gathers container configuration that must be loaded at the application level

parameters:
    security.authentication.listener.anonymous.class: Claroline\CoreBundle\Listener\AnonymousAuthenticationListener
    security.logout.handler.session.class: Claroline\CoreBundle\Library\Security\LogoutHandler
    templating.locator.class: Claroline\CoreBundle\Library\Templating\Loader\TemplateLocator
    twig.controller.exception.class : Claroline\CoreBundle\Controller\CustomExceptionController

services:
    templating.locator:
        class: '%templating.locator.class%'
        arguments:
            - "@file_locator"
            - "@claroline.config.platform_config_handler"
            - "@claroline.common.theme_service"
            - %kernel.root_dir%/Resources

#    gedmo.listener.translatable:
#        class: Claroline\CoreBundle\Listener\LocaleListener
        #parent: gedmo.listener.translatable
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ @annotation_reader ] ]
#            - [ setDefaultLocale, [ %locale% ] ]
#            - [ setTranslationFallback, [ false ] ]

framework:
    test: true
