framework:
    secret:          %secret%
    router:
        resource: .
        type: dynamic
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator:      { fallback: en }
    default_locale: %locale%
    session: ~
      #cookie_lifetime: 15
    #behat needs it to be run in the prod environment, but it's located in config.yml instead.
    #test: true