stfalcon_tinymce:
    include_jquery: false
    tinymce_jquery: true
    selector: '.tinymce'
    use_callback_tinymce_init: true
    external_plugins:
            imagemanager:
                url: 'asset[bundles/clarolinecore/js/tinymce/config.js]'
    tinymce_buttons:
            ressourceLinker: # Id of the first button
                title: 'Resource Linker'
                image: 'asset[bundles/clarolinecore/images/resources/icons/res_folder.png]'
            fullscreenToggle: # Put in fullscreen in avanced mode
                title : 'toggle'
                image : 'http://claroline.net/favicon.ico'
    theme:
        simple:
            theme: 'modern'
            menubar: false
            toolbar1: 'bold italic underline | ressourceLinker | alignleft aligncenter alignright alignjustify | fullscreenToggle'
        medium:
            theme: 'modern'
            plugins:
                     - '  fullscreen, emoticons code autolink lists link image charmap print preview hr anchor pagebreak'
                     - 'searchreplace wordcount visualblocks visualchars  fullscreen'
                     - 'insertdatetime media nonbreaking save table contextmenu directionality'
            menubar: false
            toolbar1: 'bold,italic,underline,undo,redo,removeformat,cleanup,code | ressourceLinker | fullscreenToggle '
            toolbar2: 'alignleft aligncenter alignright alignjustify | emoticons lists link image charmap print preview hr anchor pagebreak '
            relative_urls : false
        advanced:
            plugins:
                - 'advlist autolink lists link image charmap print preview hr anchor pagebreak'
                - 'searchreplace wordcount visualblocks visualchars code fullscreen'
                - 'insertdatetime media nonbreaking save table contextmenu directionality'
                - 'emoticons template paste textcolor'
            toolbar1: ' undo redo | styleselect | bold italic | advlist autolink lists link image charmap print preview hr anchor pagebreak '
            toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | insertdatetime media nonbreaking save table contextmenu directionality"
            toolbar3: 'searchreplace wordcount visualblocks visualchars code'
            image_advtab: true
            templates:
                - {title: 'Test template 1', content: 'Test 1'}
                - {title: 'Test template 2', content: 'Test 2'}
